### ISSUE TITLE
NavSatStatus is always fix

### ISSUE THREAD

**Issue by ArtlyStyles** [rpng/reach_ros_node#12]
Seems the NavSatStatus in NavSatFix message is always "Fix", even in the ReachView it was "Float". Is the code correct?

**Comment by goldbattle** [comment]
I believe float is the same as an un-augmented fix (i.e. no base unit).
http://docs.ros.org/melodic/api/sensor_msgs/html/msg/NavSatStatus.html

**Comment by ArtlyStyles** [comment]
Sorry, my bad. You are right. So when we got a "Fix" in reach review, it should be "satellite fix" or "ground fix"?
