### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by deeeprun** [rpng/reach_ros_node#6]
When I built this, I got the following error. How can I fix it?

`-- ==> add_subdirectory(reach_ros_node)
CMake Error at /opt/ros/kinetic/share/roslint/cmake/roslint-extras.cmake:67 (catkin_run_tests_target):
  Unknown CMake command "catkin_run_tests_target".
Call Stack (most recent call first):
  reach_ros_node/CMakeLists.txt:16 (roslint_add_test)

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/racecar-ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/racecar-ws/build/CMakeFiles/CMakeError.log".
`

**Comment by goldbattle** [comment]
You can try commenting out the `roslint` requirements from the cmake and see if that then builds for you. Remove from the find package:
https://github.com/rpng/reach_ros_node/blob/f6e7a9d46207c2026597f19a9dfb215a59e7211f/CMakeLists.txt#L4

These two lines:
https://github.com/rpng/reach_ros_node/blob/f6e7a9d46207c2026597f19a9dfb215a59e7211f/CMakeLists.txt#L15-L16

**Comment by deeeprun** [comment]
Now I am able to build. 
Could you tell me where should I edit the "Position Output"?

**Comment by goldbattle** [comment]
I would take a look at their docs:
https://docs.emlid.com/reach/common/reachview/position-output/

**Comment by deeeprun** [comment]
Still do not understand. 

I would like to use Emlid Reach M+ on a robocar car which is driven by Jetson TX2 through ROS. But I am not sure how physically M+ and TX2 computer communicate to each other. Can this be done over the USB port or a serial port such as i2c?

Also, do the Reach M+ and my TX2 have to be connected to WIFI all the time?

When I say edit the Position Output, I mean which file in this repo I should modify?

**Comment by goldbattle** [comment]
This repo connects over TCP, so you will need to be connected to the same network.
`rosrun reach_ros_node nmea_tcp_driver _host:=128.4.89.123 _port:=2234`

You can try connecting with usb, and seeing if it creates a local network `ifconfig`.
Basically, however you view the webgui is the same way you can get the information out of it.
In the example above, I view the webgui by going to my browser to that IP address.

**Comment by deeeprun** [comment]
Do you expect drones, UMV have WIFI all the time?
