### ISSUE TITLE
Reach M+ and TX2 through USB cable

### ISSUE THREAD

**Issue by deeeprun** [rpng/reach_ros_node#7]
Hi, I am building a Robocar which is driven by Nvidia Jetson TX2 with sensors like Lidar, camera, and IMU. Now I could like to add GPS (Emlid Reach M+). I connect the M+ and Nvidia Jetson TX2 through USB cable. This way, M+ is powered by the TX2 and I do not need addition battery for it. However, with this setup, can I use this repo? Can I read the position data from USB?

**Comment by goldbattle** [comment]
I don't have access to my unit due to the covid virus, but looking at the forums you should be able to. If I remember correctly, after plugging it in on my ubuntu laptop it auto-connected as an ethernet interface.
https://community.emlid.com/t/gps-data-over-usb/6387

**Comment by deeeprun** [comment]
@goldbattle Thanks for the post. However, for this line:

`nc 192.168.2.15 7777`

What is ip "192.168.2.15"? Do you mean if I connect my USB to nc 192.168.2.2, I could always call nc 192.168.2.15 when I run the "nc" command?

**Comment by goldbattle** [comment]
When you connect it on usb, you can see if it shows up in `ifconfig`.
I would first try to get to view the gui over 192.168.2.1.
The ip you use for this ros node should be the same one you reach the gui over.

**Comment by deeeprun** [comment]
When I check ifconfig, my usb2 (emlid Reach M+) ip is 192.168.2.65

However, if I run `nc 192.168.2.65 7777`, I do not get any signal. 

If I run `nc 192.168.2.15 7777`, I can see the the signal.

However, when I run the ros node,  it crashed with the following messages:

nvidia@tegra-ubuntu:~/racecar-ws$ rosrun reach_ros_node nmea_tcp_driver _host:=192.168.2.15 _port:=7777
Traceback (most recent call last):
  File "/home/nvidia/racecar-ws/src/reach_ros_node/scripts/nmea_tcp_driver", line 132, in <module>
    rospy.init_node('reach_ros_node')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 326, in init_node
    _init_node_params(argv, name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 186, in _init_node_params
    set_param(rosgraph.names.PRIV_NAME + param_name, param_value)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 514, in set_param
    _param_server[param_name] = param_value #MasterProxy does all the magic for us
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msproxy.py", line 148, in __setitem__
    self.target.setParam(rospy.names.get_caller_id(), rospy.names.resolve_name(key), val)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1069, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 907, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 846, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by goldbattle** [comment]
I am not sure what the `nc` command does. Ifconfig should give you what your computer ip is, the gateway is normally `192.168.X.1` but [might be different](https://unix.stackexchange.com/questions/23383/show-gateway-ip-address-when-performing-ifconfig-command). Can you view the reachview gui in your browser on that IP? That is the first step.

Edit: Have you also enabled the positional output in reachview for port 7777?

**Comment by deeeprun** [comment]
The nc command is from your post above: 

https://community.emlid.com/t/gps-data-over-usb/6387

**Comment by deeeprun** [comment]
I have enabled port 7777 in reach view. 

I think I successfully connected Reach M+ to my TX2 and TX2 can read the position data Reach M+ post. However, the ROS node crashed for some reason.

**Comment by deeeprun** [comment]
Sorry, my bad. I have not start the ROSCore yet. 

After I started ROSCore, I got the following messages:

[WARN] [1585170310.679152]: Sentence type 'ZDA' not in parse map, ignoring.
[WARN] [1585170310.681401]: Failed to parse NMEA sentence. Sentence was: $GNZDA,,,,,,*56
[ERROR] [1585170310.870056]: Value error, likely due to missing fields in the NMEA message. Error was: invalid literal for int() with base 10: ''.
[WARN] [1585170310.877789]: Sentence type 'ZDA' not in parse map, ignoring.
[WARN] [1585170310.879966]: Failed to parse NMEA sentence. Sentence was: $GNZDA,,,,,,*56
[ERROR] [1585170311.070357]: Value error, likely due to missing fields in the NMEA message. Error was: invalid literal for int() with base 10: ''.

I think this is OK, because I am working inside with my Reach M+, and my Reach M+ is not connected to antenna. 

What do you think?

**Comment by goldbattle** [comment]
So looks like it is connected, but is erroring since the message is empty.
Do you know what line it is erroring on?

**Comment by goldbattle** [comment]
Can you try pulling the latest, it might have been in this parsing of the timestamp since it wasn't using the safe functions (i.e. if the string is empty this would fail).
https://github.com/rpng/reach_ros_node/commit/3d740a0e9ec47c8ed7544148bac771dd1343bb6a

**Comment by deeeprun** [comment]
I think it is because of my device setup. The device is indoor without antenna. When I run "nc", I also saw no data was output. I will test more with antenna outside.
